/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as ReleasesRouteImport } from './routes/releases'
import { Route as DashActivityRouteImport } from './routes/_dash.activity'
import { Route as DashAnalyticsRouteImport } from './routes/_dash.analytics'
import { Route as DashBestSharesRouteImport } from './routes/_dash.best-shares'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashDebenturesRouteImport } from './routes/_dash.debentures'
import { Route as DashIpoRouteImport } from './routes/_dash.ipo'
import { Route as DashMarketRouteImport } from './routes/_dash.market'
import { Route as DashMutualFundsRouteImport } from './routes/_dash.mutual-funds'
import { Route as DashPortfolioRouteImport } from './routes/_dash.portfolio'
import { Route as DashProfileRouteImport } from './routes/_dash.profile'
import { Route as DashReportsRouteImport } from './routes/_dash.reports'
import { Route as DashSettingsRouteImport } from './routes/_dash.settings'
import { Route as DashTerminalRouteImport } from './routes/_dash.terminal'
import { Route as DashToolsRouteImport } from './routes/_dash.tools'
import { Route as DashTransactionsRouteImport } from './routes/_dash.transactions'
import { Route as DashWaccRouteImport } from './routes/_dash.wacc'
import { Route as ApiPdfRouteImport } from './routes/api.pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const ReleasesRoute = ReleasesRouteImport.update({
  id: '/releases',
  path: '/releases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashActivityRoute = DashActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashRoute,
} as any)
const DashAnalyticsRoute = DashAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashRoute,
} as any)
const DashBestSharesRoute = DashBestSharesRouteImport.update({
  id: '/best-shares',
  path: '/best-shares',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashDebenturesRoute = DashDebenturesRouteImport.update({
  id: '/debentures',
  path: '/debentures',
  getParentRoute: () => DashRoute,
} as any)
const DashIpoRoute = DashIpoRouteImport.update({
  id: '/ipo',
  path: '/ipo',
  getParentRoute: () => DashRoute,
} as any)
const DashMarketRoute = DashMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashRoute,
} as any)
const DashMutualFundsRoute = DashMutualFundsRouteImport.update({
  id: '/mutual-funds',
  path: '/mutual-funds',
  getParentRoute: () => DashRoute,
} as any)
const DashPortfolioRoute = DashPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => DashRoute,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashReportsRoute = DashReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashRoute,
} as any)
const DashSettingsRoute = DashSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashRoute,
} as any)
const DashTerminalRoute = DashTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => DashRoute,
} as any)
const DashToolsRoute = DashToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => DashRoute,
} as any)
const DashTransactionsRoute = DashTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => DashRoute,
} as any)
const DashWaccRoute = DashWaccRouteImport.update({
  id: '/wacc',
  path: '/wacc',
  getParentRoute: () => DashRoute,
} as any)
const ApiPdfRoute = ApiPdfRouteImport.update({
  id: '/api/pdf',
  path: '/api/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/releases': typeof ReleasesRoute
  '/activity': typeof DashActivityRoute
  '/analytics': typeof DashAnalyticsRoute
  '/best-shares': typeof DashBestSharesRoute
  '/dashboard': typeof DashDashboardRoute
  '/debentures': typeof DashDebenturesRoute
  '/ipo': typeof DashIpoRoute
  '/market': typeof DashMarketRoute
  '/mutual-funds': typeof DashMutualFundsRoute
  '/portfolio': typeof DashPortfolioRoute
  '/profile': typeof DashProfileRoute
  '/reports': typeof DashReportsRoute
  '/settings': typeof DashSettingsRoute
  '/terminal': typeof DashTerminalRoute
  '/tools': typeof DashToolsRoute
  '/transactions': typeof DashTransactionsRoute
  '/wacc': typeof DashWaccRoute
  '/api/pdf': typeof ApiPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/releases': typeof ReleasesRoute
  '/activity': typeof DashActivityRoute
  '/analytics': typeof DashAnalyticsRoute
  '/best-shares': typeof DashBestSharesRoute
  '/dashboard': typeof DashDashboardRoute
  '/debentures': typeof DashDebenturesRoute
  '/ipo': typeof DashIpoRoute
  '/market': typeof DashMarketRoute
  '/mutual-funds': typeof DashMutualFundsRoute
  '/portfolio': typeof DashPortfolioRoute
  '/profile': typeof DashProfileRoute
  '/reports': typeof DashReportsRoute
  '/settings': typeof DashSettingsRoute
  '/terminal': typeof DashTerminalRoute
  '/tools': typeof DashToolsRoute
  '/transactions': typeof DashTransactionsRoute
  '/wacc': typeof DashWaccRoute
  '/api/pdf': typeof ApiPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/releases': typeof ReleasesRoute
  '/_dash/activity': typeof DashActivityRoute
  '/_dash/analytics': typeof DashAnalyticsRoute
  '/_dash/best-shares': typeof DashBestSharesRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/debentures': typeof DashDebenturesRoute
  '/_dash/ipo': typeof DashIpoRoute
  '/_dash/market': typeof DashMarketRoute
  '/_dash/mutual-funds': typeof DashMutualFundsRoute
  '/_dash/portfolio': typeof DashPortfolioRoute
  '/_dash/profile': typeof DashProfileRoute
  '/_dash/reports': typeof DashReportsRoute
  '/_dash/settings': typeof DashSettingsRoute
  '/_dash/terminal': typeof DashTerminalRoute
  '/_dash/tools': typeof DashToolsRoute
  '/_dash/transactions': typeof DashTransactionsRoute
  '/_dash/wacc': typeof DashWaccRoute
  '/api/pdf': typeof ApiPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/releases'
    | '/activity'
    | '/analytics'
    | '/best-shares'
    | '/dashboard'
    | '/debentures'
    | '/ipo'
    | '/market'
    | '/mutual-funds'
    | '/portfolio'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/terminal'
    | '/tools'
    | '/transactions'
    | '/wacc'
    | '/api/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/releases'
    | '/activity'
    | '/analytics'
    | '/best-shares'
    | '/dashboard'
    | '/debentures'
    | '/ipo'
    | '/market'
    | '/mutual-funds'
    | '/portfolio'
    | '/profile'
    | '/reports'
    | '/settings'
    | '/terminal'
    | '/tools'
    | '/transactions'
    | '/wacc'
    | '/api/pdf'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/releases'
    | '/_dash/activity'
    | '/_dash/analytics'
    | '/_dash/best-shares'
    | '/_dash/dashboard'
    | '/_dash/debentures'
    | '/_dash/ipo'
    | '/_dash/market'
    | '/_dash/mutual-funds'
    | '/_dash/portfolio'
    | '/_dash/profile'
    | '/_dash/reports'
    | '/_dash/settings'
    | '/_dash/terminal'
    | '/_dash/tools'
    | '/_dash/transactions'
    | '/_dash/wacc'
    | '/api/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  ReleasesRoute: typeof ReleasesRoute
  ApiPdfRoute: typeof ApiPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/releases': {
      id: '/releases'
      path: '/releases'
      fullPath: '/releases'
      preLoaderRoute: typeof ReleasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/activity': {
      id: '/_dash/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashActivityRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/analytics': {
      id: '/_dash/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof DashAnalyticsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/best-shares': {
      id: '/_dash/best-shares'
      path: '/best-shares'
      fullPath: '/best-shares'
      preLoaderRoute: typeof DashBestSharesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/debentures': {
      id: '/_dash/debentures'
      path: '/debentures'
      fullPath: '/debentures'
      preLoaderRoute: typeof DashDebenturesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/ipo': {
      id: '/_dash/ipo'
      path: '/ipo'
      fullPath: '/ipo'
      preLoaderRoute: typeof DashIpoRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/market': {
      id: '/_dash/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof DashMarketRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/mutual-funds': {
      id: '/_dash/mutual-funds'
      path: '/mutual-funds'
      fullPath: '/mutual-funds'
      preLoaderRoute: typeof DashMutualFundsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/portfolio': {
      id: '/_dash/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof DashPortfolioRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/reports': {
      id: '/_dash/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashReportsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/settings': {
      id: '/_dash/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashSettingsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/terminal': {
      id: '/_dash/terminal'
      path: '/terminal'
      fullPath: '/terminal'
      preLoaderRoute: typeof DashTerminalRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/tools': {
      id: '/_dash/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof DashToolsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/transactions': {
      id: '/_dash/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof DashTransactionsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/wacc': {
      id: '/_dash/wacc'
      path: '/wacc'
      fullPath: '/wacc'
      preLoaderRoute: typeof DashWaccRouteImport
      parentRoute: typeof DashRoute
    }
    '/api/pdf': {
      id: '/api/pdf'
      path: '/api/pdf'
      fullPath: '/api/pdf'
      preLoaderRoute: typeof ApiPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashRouteChildren {
  DashActivityRoute: typeof DashActivityRoute
  DashAnalyticsRoute: typeof DashAnalyticsRoute
  DashBestSharesRoute: typeof DashBestSharesRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashDebenturesRoute: typeof DashDebenturesRoute
  DashIpoRoute: typeof DashIpoRoute
  DashMarketRoute: typeof DashMarketRoute
  DashMutualFundsRoute: typeof DashMutualFundsRoute
  DashPortfolioRoute: typeof DashPortfolioRoute
  DashProfileRoute: typeof DashProfileRoute
  DashReportsRoute: typeof DashReportsRoute
  DashSettingsRoute: typeof DashSettingsRoute
  DashTerminalRoute: typeof DashTerminalRoute
  DashToolsRoute: typeof DashToolsRoute
  DashTransactionsRoute: typeof DashTransactionsRoute
  DashWaccRoute: typeof DashWaccRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivityRoute: DashActivityRoute,
  DashAnalyticsRoute: DashAnalyticsRoute,
  DashBestSharesRoute: DashBestSharesRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashDebenturesRoute: DashDebenturesRoute,
  DashIpoRoute: DashIpoRoute,
  DashMarketRoute: DashMarketRoute,
  DashMutualFundsRoute: DashMutualFundsRoute,
  DashPortfolioRoute: DashPortfolioRoute,
  DashProfileRoute: DashProfileRoute,
  DashReportsRoute: DashReportsRoute,
  DashSettingsRoute: DashSettingsRoute,
  DashTerminalRoute: DashTerminalRoute,
  DashToolsRoute: DashToolsRoute,
  DashTransactionsRoute: DashTransactionsRoute,
  DashWaccRoute: DashWaccRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  ReleasesRoute: ReleasesRoute,
  ApiPdfRoute: ApiPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
